# config/routes.yaml

# articles
index:
    path: /
    controller: App\Controller\ArticleController::page

index_page:
    path: /page/{number}
    controller: App\Controller\ArticleController::page

article:
    path: /article/{article_id}
    controller: App\Controller\ArticleController::article

new_article:
    path: /newArticle
    controller: App\Controller\ArticleController::newArticle

edit_article:
    path: /editArticle/{number}
    controller: App\Controller\ArticleController::editArticle

# Comment Controller
add_article_comment:
    path: /addComment
    controller: App\Controller\CommentController::addComment

get_article_comments:
    path: /getComments/{article_id}
    controller: App\Controller\CommentController::getComments

delete_article_comments:
    path: /deleteComment/{comment_id}
    controller: App\Controller\CommentController::deleteComment


# CommentVote Controller
set_article_comment_vote:
    path: /setCommentVote
    controller: App\Controller\CommentLikeController::setCommentVote
    
get_article_comment_vote:
    path: /getUserCommentVote/{comment_id}
    controller: App\Controller\CommentLikeController::getUserCommentVote

# Security Controller
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

profile:
    path: /profile
    controller: App\Controller\SecurityController::profile

# Registration Contoller
register:
    path: /register
    controller: App\Controller\RegistrationController::register

# Item Controller
item:
    path: /item
    controller: App\Controller\ItemController::item

# Default Controller
index_path:
    path: /{path}
    controller: App\Controller\DefaultController::index
