# config/routes.yaml

# articles
index:
    path: /
    controller: App\Controller\ArticleController::page

index_page:
    path: /page/{number}
    controller: App\Controller\ArticleController::page

article:
    path: /article/{article_id}
    controller: App\Controller\ArticleController::article

new_article:
    path: /newArticle
    controller: App\Controller\ArticleController::newArticle

edit_article:
    path: /editArticle/{number}
    controller: App\Controller\ArticleController::editArticle

# Comment Controller
add_comment:
    path: /addComment/{type}
    controller: App\Controller\CommentController::addComment

get_comments:
    path: /getComments/{type}/{type_id}
    controller: App\Controller\CommentController::getComments

delete_comments:
    path: /deleteComment/{comment_id}
    controller: App\Controller\CommentController::deleteComment

edit_comments:
    path: /editComment/{comment_id}
    controller: App\Controller\CommentController::editComment


# CommentVote Controller
set_article_comment_vote:
    path: /setCommentVote
    controller: App\Controller\CommentLikeController::setCommentVote
    
get_article_comment_vote:
    path: /getUserCommentVote/{comment_id}
    controller: App\Controller\CommentLikeController::getUserCommentVote

# Security Controller
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

profile:
    path: /profile
    controller: App\Controller\SecurityController::profile

# Registration Contoller
register:
    path: /register
    controller: App\Controller\RegistrationController::register

# Item Controller
item:
    path: /item
    controller: App\Controller\ItemController::item

item_info:
    path: /item/{item_id}
    controller: App\Controller\ItemController::item_info

serach_items:
    path: /searchItems
    controller: App\Controller\ItemController::searchItems

# Quest Controller
quest:
    path: /quest
    controller: App\Controller\QuestController::quest

quest_info:
    path: /quest/{quest_id}
    controller: App\Controller\QuestController::quest_info

serach_quests:
    path: /searchQuests
    controller: App\Controller\QuestController::searchQuests

# NPC Controller
npc:
    path: /npc
    controller: App\Controller\NpcController::npc

npc_info:
    path: /npc/{npc_id}
    controller: App\Controller\NpcController::npcInfo

serach_npcs:
    path: /searchNpcs
    controller: App\Controller\NpcController::searchNpcs

# Location Controller
location:
    path: /location/{location_id}
    controller: App\Controller\LocationController::location

# Default Controller

index_path:
    path: /{path}
    controller: App\Controller\DefaultController::index
